import { defineConfig } from "oxlint";

export default defineConfig({
  ignorePatterns: [
    "dist/**",
    ".agent/**",
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".continue/**",
    ".cursor/**",
    ".gemini/**",
    ".opencode/**",
    ".pi/**",
    ".roo/**",
    ".windsurf/**",
    "tools/oxlint/**",
  ],
  jsPlugins: [
    { name: "kubeflock", specifier: "./tools/oxlint/index.ts" },
    { name: "kubeflock-effect", specifier: "./tools/oxlint/effect/index.ts" },
  ],
  rules: {
    "kubeflock/no-chained-type-assertions": "error",
    "kubeflock/no-conditional-empty-object-spread": "error",
    "kubeflock/no-known-value-widening": "error",
    "kubeflock/no-module-mocking": "error",
    "kubeflock/no-object-parameters": "error",
    "kubeflock/no-reflect-apply": "error",
    "kubeflock/no-reflect-get": "error",
    "kubeflock/no-runtime-typeof": "error",
    "kubeflock/no-shape-in-symbol-names": "error",
    "kubeflock/no-unknown-parameters": "error",
    "kubeflock/no-unknown-returns": "error",
    "kubeflock/no-unknown-type-aliases": "error",
    "kubeflock/no-unsafe-dictionary-type": "error",
    "kubeflock/no-widen-then-assert": "error",
    "kubeflock/require-safety-comment-for-type-assertion": "error",
    "kubeflock-effect/no-service-constructor-imports": "error",
  },
});
