apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeflock-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kubeflock.labels" . | nindent 4 }}
data:
{{- range .Values.credentials }}
  {{ .name }}: {{ dict "secret" .secretName "key" .key "environment" .environment | toJson | quote }}
{{- end }}
